### Get all movies
get http://localhost:3000/movies

### Get a movie by id
get http://localhost:3000/movies/1ca80c4e-036d-11f0-98d3-18c04d885ab8

### Get all movies by genre
get http://localhost:3000/movies?genre=Comedy

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "genre": ["Crime", "Drama"],
    "rate": 10,
    "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
}

###Update a movie
PATCH http://localhost:3000/movies/192e4699-932b-4689-94d6-12ce883f6e29
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "genre": ["Crime", "Drama"],
    "rate": 10,
    "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
}

###Update a movie partialy
PATCH http://localhost:3000/movies/9c4c12fe-7914-4530-af5e-2762c5623484
Content-Type: application/json

{
    "genre": ["Comedy", "Drama", "Thriller", "action"]
}